// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLTBYqWJ_STGT8FZ6rdLAH0G6Y_ZvBCf4',
    appId: '1:368964350199:web:ba67c5f367582cc38ca3f2',
    messagingSenderId: '368964350199',
    projectId: 'project-donations-33a68',
    authDomain: 'project-donations-33a68.firebaseapp.com',
    storageBucket: 'project-donations-33a68.firebasestorage.app',
    measurementId: 'G-GSQG73SLQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3Dnk6EQFToTlZ9j-BdXvc8oSlRgkPzs',
    appId: '1:368964350199:android:4ce9bf2d510162068ca3f2',
    messagingSenderId: '368964350199',
    projectId: 'project-donations-33a68',
    storageBucket: 'project-donations-33a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrKJ33-c7UoNv5WK_dQ4CpwhPhLfE1HmA',
    appId: '1:368964350199:ios:4f0e5840053e24788ca3f2',
    messagingSenderId: '368964350199',
    projectId: 'project-donations-33a68',
    storageBucket: 'project-donations-33a68.firebasestorage.app',
    iosBundleId: 'com.example.appdonationsgestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrKJ33-c7UoNv5WK_dQ4CpwhPhLfE1HmA',
    appId: '1:368964350199:ios:4f0e5840053e24788ca3f2',
    messagingSenderId: '368964350199',
    projectId: 'project-donations-33a68',
    storageBucket: 'project-donations-33a68.firebasestorage.app',
    iosBundleId: 'com.example.appdonationsgestor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLTBYqWJ_STGT8FZ6rdLAH0G6Y_ZvBCf4',
    appId: '1:368964350199:web:a0936746c8aded8a8ca3f2',
    messagingSenderId: '368964350199',
    projectId: 'project-donations-33a68',
    authDomain: 'project-donations-33a68.firebaseapp.com',
    storageBucket: 'project-donations-33a68.firebasestorage.app',
    measurementId: 'G-T9R5K81637',
  );

}