// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2UE5iGdK-wHyZKB6eiOwIeJxE6hrzzo8',
    appId: '1:933781600794:web:8ad89ad0a542c641972fa3',
    messagingSenderId: '933781600794',
    projectId: 'projeto-doacoes-2025',
    authDomain: 'projeto-doacoes-2025.firebaseapp.com',
    storageBucket: 'projeto-doacoes-2025.firebasestorage.app',
    measurementId: 'G-0R09HTKGKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYvCpclS1_1uhZokspvd0r6Q9SoZUbQo',
    appId: '1:933781600794:android:44b84cd702ebc270972fa3',
    messagingSenderId: '933781600794',
    projectId: 'projeto-doacoes-2025',
    storageBucket: 'projeto-doacoes-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjqhWetvUGJzfeIpzILzZRilCgC_ioszI',
    appId: '1:933781600794:ios:93d8210a3a947aa1972fa3',
    messagingSenderId: '933781600794',
    projectId: 'projeto-doacoes-2025',
    storageBucket: 'projeto-doacoes-2025.firebasestorage.app',
    iosBundleId: 'com.example.appdonationsgestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjqhWetvUGJzfeIpzILzZRilCgC_ioszI',
    appId: '1:933781600794:ios:93d8210a3a947aa1972fa3',
    messagingSenderId: '933781600794',
    projectId: 'projeto-doacoes-2025',
    storageBucket: 'projeto-doacoes-2025.firebasestorage.app',
    iosBundleId: 'com.example.appdonationsgestor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2UE5iGdK-wHyZKB6eiOwIeJxE6hrzzo8',
    appId: '1:933781600794:web:d1422226cbb1c631972fa3',
    messagingSenderId: '933781600794',
    projectId: 'projeto-doacoes-2025',
    authDomain: 'projeto-doacoes-2025.firebaseapp.com',
    storageBucket: 'projeto-doacoes-2025.firebasestorage.app',
    measurementId: 'G-EP4RNDFXV4',
  );

}